# Generated by Django 5.1.4 on 2026-06-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_alert_qty', models.IntegerField(default=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
